# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
  xterm-color|*-256color) color_prompt=yes;;
esac

if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
  # We have color support; assume it's compliant with Ecma-48
  # (ISO/IEC-6429). (Lack of such support is extremely rare, and such
  # a case would tend to support setf rather than setaf.)
  color_prompt=yes
else
  color_prompt=
fi

### Terminal Prompt
# fancy colors for our prompt
BLD="\[\e[1m\]"   # hicolor
UNL="\[\e[4m\]"   # underline
INV="\[\e[7m\]"   # inverse background and foreground
FBLK="\[\e[30m\]" # foreground black
FRED="\[\e[31m\]" # foreground red
FGRN="\[\e[32m\]" # foreground green
FYEL="\[\e[33m\]" # foreground yellow
FBLU="\[\e[34m\]" # foreground blue
FMAG="\[\e[35m\]" # foreground magenta
FCYN="\[\e[36m\]" # foreground cyan
FWHT="\[\e[37m\]" # foreground white
BBLK="\[\e[40m\]" # background black
BRED="\[\e[41m\]" # background red
BGRN="\[\e[42m\]" # background green
BYEL="\[\e[43m\]" # background yellow
BBLU="\[\e[44m\]" # background blue
BMAG="\[\e[45m\]" # background magenta
BCYN="\[\e[46m\]" # background cyan
BWHT="\[\e[47m\]" # background white
RST="\[\e[0m\]"   # reset

# Test user type:
if [[ ${USER} == "root" ]]; then
  SU="$FRED"
else
  SU="$FGRN"
fi

running_in_docker() {
  awk -F/ '$2 == "docker"' /proc/self/cgroup | read
}

running_in_docker
if [ $? -eq 0 ] ; then
  DOCKER="-docker"
else
  DOCKER=""
fi

if [ "$color_prompt" = "yes" ]; then
  PS1="$BLD$SU\u$FYEL@$FRED\h$DOCKER$RST $BLD$FBLU\w$RST \n$ "
  PS2="$BLD$FGRN> $RST"
else
  PS1='\u@\h'$DOCKER' \w\$ '
fi

# Use this if lesspipe.sh exists.
export LESSOPEN='|/usr/bin/lesspipe.sh %s 2>&-'

# -i like vim smartcase, -w highlight unread, -g highlight first match, -M verbose prompt
# -M no init termcap, -F quit if only one screen, -P Prompt, -n No line numbers
export LESS='-i -n -w -F -M -X -R -P%t?f%f \
:stdin .?pb%pb\%:?lbLine %lb:?bbByte %bb:-...'

# LESS man page colors (makes Man pages more readable).
# Start blink
export LESS_TERMCAP_mb=$(tput bold)
# Start bold
export LESS_TERMCAP_md=$(tput bold; tput setaf 5)
# Turn off bold, blink, underline
export LESS_TERMCAP_me=$(tput sgr0)
# Start, Stop standout
export LESS_TERMCAP_so=$(tput smso; tput setaf 1; tput setab 7)
export LESS_TERMCAP_se=$(tput sgr0)
# Start, Stop underline
export LESS_TERMCAP_us=$(tput smul)
export LESS_TERMCAP_ue=$(tput rmul)
# colored GCC warnings and errors
export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'

# See man bash
shopt -s autocd
shopt -s checkwinsize
# shopt -s cdspell
shopt -s checkhash
shopt -s checkjobs
shopt -s cmdhist
shopt -s histappend

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoredups

export PATH="$HOME/.local/bin:$PATH"
export PATH="/usr/lib64/ccache:$PATH"
export PAGER=less

if [ "" = "$DISPLAY" ] ; then
  export EDITOR=vim
else
  export EDITOR=${HOME}/.editor
fi

# GHS Configuration
# Host defines.....
export GHS_LMHOST="#ghslm1,ghslm2,ghslm3"
export GHS_LMWHICH="ghs"

export MULTI_DIR=/home/multi/tools_devl/working
export COMP_DIR=/home/compiler/tools_devl/working
#export COMP_DIR=/home/compiler/tools_devl/devl-2019-03-09/
export BRANCH_DIR=/home/landshark/sean.wilson/branches/

PATH=/home/steeply/valmart/tools/dtc:${PATH}
PATH=${PATH}:${COMP_DIR}/linux86-comp-deploy
PATH=${PATH}:${MULTI_DIR}/linux86-ide-deploy
PATH=${PATH}:${MULTI_DIR}/sitescripts
PATH=${RTOS_DIR}/privutils/svn_commit:${PATH}
PATH=${RTOS_DIR}/privutils/gcomponent:${PATH}
PATH=${PATH}:/archive/script
PATH=${PATH}:/home/advprod/crucible
PYTHONPATH=${RTOS_DIR}/privutils/gcomponent:${PYTHONPATH}
export PYTHONPATH
export PATH

[ -f ~/.bash_aliases ] && source ~/.bash_aliases

[ -f ~/.fzf.bash ] && source ~/.fzf.bash
