#!/bin/bash


# See 'killps' for example of use.
function ask()
{
    echo -n "$@" '[y/n] ' ; read ans
    case "$ans" in
        y*|Y*) return 0 ;;
        *) return 1 ;;
    esac
}

# kill by process name
function killps()
{
    local pid pname sig="-TERM"   # default signal
    if [ "$#" -lt 1 ] || [ "$#" -gt 2 ]; then
        echo "Usage: killps [-SIGNAL] pattern"
        return;
    fi
    if [ $# = 2 ]; then sig=$1 ; fi
    for pid in $(my_ps| awk '!/awk/ && $0~pat { print $1 }' pat=${!#} )
    do
        pname=$(my_ps | awk '$1~var { print $5 }' var=$pid )
        if ask "Kill process $pid <$pname> with signal $sig?"
            then kill $sig $pid
        fi
    done
}

# Print colors to the terminal.
function colors() {
    _color(){
        for c; do
            printf '\e[48;5;%dm%03d' $c $c
        done
        printf '\e[0m \n'
    }

    IFS=$' \t\n'
    _color {0..15}
    for ((i=0;i<6;i++)); do
        _color $(seq $((i*36+16)) $((i*36+51)))
    done
    _color {232..255}

}

# Path/Utility functions
unixpath2dos () {
  echo "$1" | sed "s/\//\\\/g"
}
dospath2unix () {
  sed -e 's~\\~/~g' -e 's~J:~/usr~' <<< "$1"
}
path() {
  echo $PATH | tr : "\n"
}
catline() {
  head -n $1 $2 | tail -n 1
}

# Log/productivity functions
function log() {
  v "" --forward -c Log
}

# Diff svn from the branch point
svn_diff_cp () {
  svn diff -r `svn log --stop-on-copy -q | tail -n2 | head -n1 | grep -Eo 'r[0-9]+'`:HEAD
}
svn_clean () {
  svn status | grep ^\? | cut -c9- | xargs -d \\n rm -r
}
alias svnst="svn status -q"
alias svnr="svn resolve --accept working"
alias sup="svn up --non-interactive; echo -e \"\\\\a\"; sleep .25; echo -e \"\\\\a\""

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    alias dir='dir --color=auto'
    alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

alias ll='ls -l'
alias la='ls -la'

alias ag="ag -U"
alias grep="grep --exclude-dir .svn"

# Typo aliases
alias cd..='cd ..'
alias l='ls'
alias sl='ls'


# Green Hills
alias locate1='locate -n1'
alias unreserve='/home/apvalmart/rtos_val/tools/support/bfunreserve'
alias cdi="cd_issue"
alias cdw="cd /home/landshark/sean.wilson"
alias cdb="cd /home/landshark/sean.wilson/git/working"
# alias gbas="sup && ./builds-ep/build_all.sh"
# alias svn16="/archive/subversion/1.6/subversion-1.6.9/subversion/svn/svn"
# alias svn17="/archive/subversion/1.7/subversion-1.7.17/subversion/svn/svn"
# other aliases
alias diffview='meld'
alias dv="diffview"
# alias clgrep='clgrep --rtos'
# alias unigui='${RTOS_DIR}/rtos_val/shared/unival/unigui.py'
# # alias multi='multi -sr_private' # scottr this fails to open BSP directories
# alias mpm='${TOOLS_DIR}/mprojmgr'
# alias ghsgcc='${TOOLS_DIR}/gcc'
# alias mhist="me -historybrowser"
# alias gba="./builds-ep/build_all.sh"
# alias ba="./builds-ep/build_all.sh"
alias printsource="enscript -C -DDuplex:true -DCollate:true -G2rE -f Courier@6 --margins=20:20:15:15"
#alias ivncviewer="/home/integrity/rtos_val/bin/vncviewer/linux86/vncviewer"

alias ct="ctags -R --exclude=\"INTEGRITY-docs\" --exclude=\"manuals\" --exclude=\"python\""
alias psirun="/home/apvalmart/rtos_val/psival/system/psirun.py"

function _format_commit_message() {
  svn log -c $1 http://rtosvc |\
    sed -e ':a;N;$!ba;s/Change reviewed by (user ID):.*//' |\
    sed -e ':a;N;$!ba;s/Reason for commit policy violation:.*//' |\
    sed -e 's/^/> /'
}

function format_commit_messages {
  for cid in $@ ; do
    _format_commit_message $cid
  done
}

function create_trunk_issue() {
  pushd "$BRANCH_DIR"
    mkdir "$1"
    cd "$1"
      mkdir patches

      svn co http://rtosvc/trunk/rtos trunk
      cd trunk
        ./setup
        ./products/integrity_additions_bto.sh
}

function co_trunk() {
  svn co http://rtosvc/trunk/rtos trunk
  cd trunk
    ./setup
    ./products/integrity_additions_bto.sh
}

function create_issue() {
  pushd "$BRANCH_DIR"
    mkdir "$1"
    cd "$1"
      mkdir patches

      svn co http://rtosvc/trunk/rtos trunk
      cd trunk
        ./setup
        ./products/integrity_additions_bto.sh
      cd ..

      svn co http://rtosvc/branches/ap/rtos-i11.7/rtos i11.7
      cd i11.7
        ./setup
        ./products/integrity_additions_multivisor.sh
      cd ..

      svn co http://rtosvc/branches/ap/trunk/rtos aptrunk
      cd aptrunk
        ./setup
        ./products/integrity_additions_multivisor.sh
      cd ..
    cd .. # Issue dir
  popd # BRANCH_DIR
}

function cd_issue() {
  cd "$BRANCH_DIR/$1"
}
