[ -f ~/.sharedrc ] && source ~/.sharedrc

# Enable bash completion
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
  xterm-color|*-256color) color_prompt=yes;;
esac

if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
  # We have color support; assume it's compliant with Ecma-48
  # (ISO/IEC-6429). (Lack of such support is extremely rare, and such
  # a case would tend to support setf rather than setaf.)
  color_prompt=yes
else
  color_prompt=
fi

### Terminal Prompt
# fancy colors for our prompt
RST="\[\e[0m\]"   # reset
BLD="\[\e[1m\]"   # hicolor
UNL="\[\e[4m\]"   # underline
INV="\[\e[7m\]"   # inverse background and foreground
FBLK="\[\e[30m\]" # foreground black
FRED="\[\e[31m\]" # foreground red
FGRN="\[\e[32m\]" # foreground green
FYEL="\[\e[33m\]" # foreground yellow
FBLU="\[\e[34m\]" # foreground blue
FMAG="\[\e[35m\]" # foreground magenta
FCYN="\[\e[36m\]" # foreground cyan
FWHT="\[\e[37m\]" # foreground white
BBLK="\[\e[40m\]" # background black
BRED="\[\e[41m\]" # background red
BGRN="\[\e[42m\]" # background green
BYEL="\[\e[43m\]" # background yellow
BBLU="\[\e[44m\]" # background blue
BMAG="\[\e[45m\]" # background magenta
BCYN="\[\e[46m\]" # background cyan
BWHT="\[\e[47m\]" # background white

# Test user type:
if [[ ${USER} == "root" ]]; then
  SU="$FRED"
else
  SU="$FGRN"
fi

if [ "$color_prompt" = "yes" ]; then
  PS1="$BLD$SU\u$FYEL@$FRED\h$RST $BLD$FBLU\w$RST \n$ "
  PS2="$BLD$FGRN> $RST"
else
  PS1='\u@\h \w\$ '
fi

# Use this if lesspipe.sh exists.
export LESSOPEN='|/usr/bin/lesspipe.sh %s 2>&-'

# -i like vim smartcase, -w highlight unread, -g highlight first match, -M verbose prompt
# -M no init termcap, -F quit if only one screen, -P Prompt, -n No line numbers
export LESS='-i -n -w -F -M -X -R -P%t?f%f \
:stdin .?pb%pb\%:?lbLine %lb:?bbByte %bb:-...'

# LESS man page colors (makes Man pages more readable).
# Start blink
export LESS_TERMCAP_mb=$(tput bold)
# Start bold
export LESS_TERMCAP_md=$(tput bold; tput setaf 5)
# Turn off bold, blink, underline
export LESS_TERMCAP_me=$(tput sgr0)
# Start, Stop standout
export LESS_TERMCAP_so=$(tput smso; tput setaf 1; tput setab 7)
export LESS_TERMCAP_se=$(tput sgr0)
# Start, Stop underline
export LESS_TERMCAP_us=$(tput smul)
export LESS_TERMCAP_ue=$(tput rmul)
# colored GCC warnings and errors
export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'

# See man bash
shopt -s autocd
shopt -s checkwinsize
# shopt -s cdspell
shopt -s checkhash
shopt -s checkjobs
shopt -s cmdhist
shopt -s histappend

# Don't put duplicate lines or lines starting with space in the history.
HISTCONTROL=ignoredups

export PAGER=less

[ -f ~/.bash_aliases ] && source ~/.bash_aliases
[ -f ~/.fzf.bash ] && source ~/.fzf.bash

if [ -d ~/.local/bashrcs ] ; then
  bashrcs=`find "$HOME/.local/bashrcs" -type f`
  for f in $bashrcs; do
    source "$f"
  done
fi
